[tool.poetry]
name = "pollypedagogymap"
version = "0.1.0"
description = ""
authors = ["cam <Cameron.j.poole@gmail.com>"]
readme = "README.md"
packages = [{include = "pollypedagogy"}]

[tool.poetry.dependencies]
python = "^3.10"
anyio = "3.6.2"
appnope = "0.1.3"
argon2-cffi = "21.3.0"
argon2-cffi-bindings = "21.2.0"
arrow = "1.2.3"
asttokens = "2.2.1"
attrs = "22.2.0"
backcall = "0.2.0"
beautifulsoup4 = "4.11.2"
bleach = "6.0.0"
build = "0.10.0"
CacheControl = "0.12.11"
certifi = "2022.12.7"
cffi = "1.15.1"
charset-normalizer = "3.1.0"
cleo = "2.0.1"
comm = "0.1.2"
crashtest = "0.4.1"
debugpy = "1.6.6"
decorator = "5.1.1"
defusedxml = "0.7.1"
distlib = "0.3.6"
dulwich = "0.21.3"
executing = "1.2.0"
fastjsonschema = "2.16.3"
filelock = "3.9.0"
fqdn = "1.5.1"
html5lib = "1.1"
idna = "3.4"
importlib-metadata = "6.0.0"
installer = "0.6.0"
ipykernel = "6.21.3"
ipython = "8.11.0"
ipython_genutils = "0.2.0"
ipywidgets = "7.7.4"
isodate = "0.6.1"
isoduration = "20.11.0"
"jaraco.classes" = "3.2.3"
jedi = "0.18.2"
Jinja2 = "3.1.2"
jsonpointer = "2.3"
jsonschema = "4.17.3"
jupyter = "1.0.0"
jupyter-console = "6.6.3"
jupyter-events = "0.6.3"
jupyter-client = "8.0.3"
jupyter-core = "5.2.0"
jupyter-server = "2.4.0"
jupyter-server-terminals = "0.4.4"
jupyterlab-pygments = "0.2.2"
jupyterlab-widgets = "1.1.3"
keplergl =  "0.3.2"
keyring = "23.13.1"
lockfile = "0.12.2"
MarkupSafe = "2.1.2"
matplotlib-inline = "0.1.6"
mistune = "2.0.5"
more-itertools = "9.1.0"
msgpack = "1.0.4"
nbclassic = "0.5.3"
nbclient = "0.7.2"
nbconvert = "7.2.9"
nbformat = "5.7.3"
nest-asyncio = "1.5.6"
notebook = "6.5.3"
notebook-shim = "0.2.2"
numpy = "1.24.2"
packaging = "23.0"
pandas = "1.5.3"
pandocfilters = "1.5.0"
parso = "0.8.3"
pexpect = "4.8.0"
pickleshare = "0.7.5"
pkginfo = "1.9.6"
platformdirs = "2.6.2"
poetry = "1.4.0"
poetry-core = "1.5.1"
poetry-plugin-export = "1.3.0"
prometheus-client = "0.16.0"
prompt-toolkit = "3.0.38"
psutil = "5.9.4"
ptyprocess = "0.7.0"
pure-eval = "0.2.2"
pycparser = "2.21"
Pygments = "2.14.0"
pyparsing = "3.0.9"
pyproject_hooks = "1.0.0"
pyrsistent = "0.19.3"
python-dateutil = "2.8.2"
python-json-logger = "2.0.7"
pytz = "2022.7.1"
PyYAML = "6.0"
pyzmq = "25.0.0"
qtconsole = "5.4.0"
QtPy = "2.3.0"
rapidfuzz = "2.13.7"
rdflib = "6.2.0"
requests = "2.28.2"
requests-toolbelt = "0.10.1"
rfc3339-validator = "0.1.4"
rfc3986-validator = "0.1.1"
Send2Trash = "1.8.0"
shellingham = "1.5.0.post1"
six = "1.16.0"
sniffio = "1.3.0"
soupsieve = "2.4"
SPARQLWrapper = "2.0.0"
stack-data = "0.6.2"
terminado = "0.17.1"
tinycss2 = "1.2.1"
tomli = "2.0.1"
tomlkit = "0.11.6"
tornado = "6.2"
traitlets = "5.9.0"
traittypes = "0.2.1"
trove-classifiers = "2023.2.20"
uri-template = "1.2.0"
urllib3 = "1.26.14"
virtualenv = "20.20.0"
wcwidth = "0.2.6"
webcolors = "1.12"
webencodings = "0.5.1"
websocket-client = "1.5.1"
widgetsnbextension = "3.6.3"
xattr = "0.10.1"
zipp = "3.15.0"
duckdb = "0.7.1"
datasette = "^0.64.2"
spatialite = "^0.0.3"
geopandas = "^0.12.2"
pyogrio = "^0.5.1"
pyarrow = "^11.0.0"
folium = "^0.14.0"
matplotlib = "^3.7.1"
mapclassify = "^2.5.0"
rpy2 = "^3.5.10"
GeoAlchemy2 = "^0.13.1"
Wikipedia-API = "^0.5.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
